"""initial schema with all tables

Revision ID: 7fe85cfe9464
Revises: 
Create Date: 2025-10-26 16:49:48.518249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe85cfe9464'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_announcements_active_priority', 'announcements', ['is_active', 'priority', 'language'], unique=False)
    op.create_table('consent_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('idx_consent_versions_active', 'consent_versions', ['is_active', 'version'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('weaviate_id', sa.String(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_sources_domain', 'knowledge_sources', ['domain'], unique=False)
    op.create_index('idx_knowledge_sources_status', 'knowledge_sources', ['ingestion_status'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_created_at'), 'knowledge_sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_url'), 'knowledge_sources', ['url'], unique=True)
    op.create_index(op.f('ix_knowledge_sources_weaviate_id'), 'knowledge_sources', ['weaviate_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('consent_version', sa.String(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sentences', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_user_session', 'chat_messages', ['user_id', 'session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forum_posts_category', 'forum_posts', ['category'], unique=False)
    op.create_index('idx_forum_posts_client_id', 'forum_posts', ['client_id'], unique=False)
    op.create_index('idx_forum_posts_user_created', 'forum_posts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_forum_posts_client_id'), 'forum_posts', ['client_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_created_at'), 'forum_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_forum_posts_id'), 'forum_posts', ['id'], unique=False)
    op.create_index(op.f('ix_forum_posts_user_id'), 'forum_posts', ['user_id'], unique=False)
    op.create_table('media_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_uploads_status', 'media_uploads', ['processing_status'], unique=False)
    op.create_index('idx_media_uploads_user_created', 'media_uploads', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_media_uploads_created_at'), 'media_uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_uploads_user_id'), 'media_uploads', ['user_id'], unique=False)
    op.create_table('sync_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conflict_resolution', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_queue_status', 'sync_queue', ['status', 'created_at'], unique=False)
    op.create_index('idx_sync_queue_user', 'sync_queue', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sync_queue_created_at'), 'sync_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_queue_user_id'), 'sync_queue', ['user_id'], unique=False)
    op.create_table('chat_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sources_message_id'), 'chat_sources', ['message_id'], unique=False)
    op.create_table('forum_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['forum_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forum_comments_post_created', 'forum_comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_forum_comments_client_id'), 'forum_comments', ['client_id'], unique=False)
    op.create_index(op.f('ix_forum_comments_created_at'), 'forum_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_forum_comments_id'), 'forum_comments', ['id'], unique=False)
    op.create_index(op.f('ix_forum_comments_post_id'), 'forum_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_forum_comments_user_id'), 'forum_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_comments_user_id'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_post_id'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_id'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_created_at'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_client_id'), table_name='forum_comments')
    op.drop_index('idx_forum_comments_post_created', table_name='forum_comments')
    op.drop_table('forum_comments')
    op.drop_index(op.f('ix_chat_sources_message_id'), table_name='chat_sources')
    op.drop_table('chat_sources')
    op.drop_index(op.f('ix_sync_queue_user_id'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_created_at'), table_name='sync_queue')
    op.drop_index('idx_sync_queue_user', table_name='sync_queue')
    op.drop_index('idx_sync_queue_status', table_name='sync_queue')
    op.drop_table('sync_queue')
    op.drop_index(op.f('ix_media_uploads_user_id'), table_name='media_uploads')
    op.drop_index(op.f('ix_media_uploads_created_at'), table_name='media_uploads')
    op.drop_index('idx_media_uploads_user_created', table_name='media_uploads')
    op.drop_index('idx_media_uploads_status', table_name='media_uploads')
    op.drop_table('media_uploads')
    op.drop_index(op.f('ix_forum_posts_user_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_created_at'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_client_id'), table_name='forum_posts')
    op.drop_index('idx_forum_posts_user_created', table_name='forum_posts')
    op.drop_index('idx_forum_posts_client_id', table_name='forum_posts')
    op.drop_index('idx_forum_posts_category', table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_user_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_sources_weaviate_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_url'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_created_at'), table_name='knowledge_sources')
    op.drop_index('idx_knowledge_sources_status', table_name='knowledge_sources')
    op.drop_index('idx_knowledge_sources_domain', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index('idx_consent_versions_active', table_name='consent_versions')
    op.drop_table('consent_versions')
    op.drop_index('idx_announcements_active_priority', table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
